# Generated by Django 5.1.1 on 2024-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('facture_date', models.DateField()),
                ('facture_relance', models.DateField()),
                ('facture_img', models.ImageField(upload_to='factures/')),
            ],
        ),
    ]
