# Generated by Django 5.1.1 on 2024-09-30 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='client_name',
            new_name='nom_du_client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='facture_img',
        ),
        migrations.AddField(
            model_name='facture',
            name='photo_de_la_facture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='users/factures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_date',
            field=models.DateField(blank=True, verbose_name='Date de la facture (Jour/Mois/Année)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_relance',
            field=models.DateField(blank=True, verbose_name="Date d'échéance (Jour/Mois/Année)"),
        ),
    ]
