# Generated by Django 5.1.1 on 2024-10-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_rename_client_name_facture_nom_du_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='nom_du_client',
            new_name='nom_client',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='photo_de_la_facture',
            new_name='photo_facture',
        ),
    ]
