# Generated by Django 5.1.1 on 2024-10-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_rename_nom_du_client_facture_nom_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facture',
            new_name='Factures',
        ),
    ]
