# Generated by Django 5.1.1 on 2024-10-04 13:04

import django.utils.timezone
import facture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_rename_facture_factures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='photo_facture',
        ),
        migrations.AddField(
            model_name='factures',
            name='fact_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=facture.models.user_directory_path),
            preserve_default=False,
        ),
    ]
