# Generated by Django 5.1.1 on 2024-10-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_remove_factures_photo_facture_factures_fact_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factures',
            old_name='fact_img',
            new_name='photo_facture',
        ),
    ]
