# Generated by Django 5.1.1 on 2024-10-04 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_rename_fact_img_factures_photo_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='nom_facture',
            field=models.CharField(default='FACT00', max_length=150),
            preserve_default=False,
        ),
    ]
